### ISSUE TITLE
Vulkan Dependencies should be bundled

### ISSUE THREAD

**Issue by A6GibKm** [flathub/net.lutris.Lutris#34]
Currently lutris//beta does not recognize Vulkan by default , `org.freedesktop.Platform.GL.default` and `org.freedesktop.Platform.GL32.default` (or their counterparts  `org.freedesktop.Platform.GL.mesa-aco` `org.freedesktop.Platform.GL32.mesa-aco`) resolve this issue and should be listed as dependencies.

**Comment by gasinvein** [comment]
These already are dependencies and should be installed by flatpak when you install Lutris.
There is a known bug with Gnome Software that it skips app extensions upon installation. Is this your case?

**Comment by A6GibKm** [comment]
My case is that when  I do `flatpak install flathub-beta net.lutris.Lutris//beta` none of those install, in fact after installing them manually a `flatpak remove --unused` tries to remove them, btw I only install stuff via cli.

**Comment by gasinvein** [comment]
Then it probably should be reported to flatpak itself. Is it reproducible with Steam beta branch?

**Comment by A6GibKm** [comment]
By the way I only see `org.freedesktop.Platform.GL32` as a dependency.

**Comment by gasinvein** [comment]
`org.freedesktop.Platform.GL32` is an extension of the app, `org.freedesktop.Platform.GL` is an extension of the runtime, used by all apps.

**Comment by A6GibKm** [comment]
I am installing it correctly adding the `//beta` to the app id?

**Comment by gasinvein** [comment]
`net.lutris.Lutris//beta` is correct, yes. `beta` here is the branch.

**Comment by A6GibKm** [comment]
This is related to https://github.com/flatpak/flatpak/issues/861?

**Comment by gasinvein** [comment]
Seems unlikely, but you better ask there anyway.

**Comment by A6GibKm** [comment]
I am closing this as it seems more of a repository / flatpak issue. I will look into it again when freedesktop 19.08 hits flathub.

**Comment by gasinvein** [comment]
>freedesktop 19.08 hits flathub

Hmm, did you install the FD.o runtime _not_ from the flathub-beta repository? If so, this may be the cause: flatpak doesn't pull extensions automatically if they come from a different remote.

**Comment by A6GibKm** [comment]
I got everything form flathub-beta, but I think one of the GL extensions is only on freedesktop-sdk repo

**Comment by A6GibKm** [comment]
I looked the manifest and I noticed it has the option `no-autodownload: true`
```yaml
org.freedesktop.Platform.GL32:
    directory: lib/i386-linux-gnu/GL
    version: "1.4"
    versions: "19.08beta;1.4"
    subdirectories: true
    no-autodownload: true
    autodelete: false
    add-ld-path: lib
    merge-dirs: vulkan/icd.d;glvnd/egl_vendor.d;OpenCL/vendors
    download-if: active-gl-driver
    enable-if: active-gl-driver
```
Is this relevant?
